import 'package:hng2_inventory_app/Database/inventory_db.dart';

final List<Product> seafoodProducts = [
  Product(
    id: '1',
    name: 'Fresh Salmon',
    code: 'SF001',
    stock: 50,
    pricePerKg: 15000.0,
    supplier: 'Blue Ocean Traders',
    imagePath: 'assets/images/salmon.jpg',
  ),
  Product(
    id: '2',
    name: 'Tilapia Fish',
    code: 'SF002',
    stock: 60,
    pricePerKg: 3000.0,
    supplier: 'Riverfresh',
    imagePath: 'assets/images/tilapia.jpg',
  ),
  Product(
    id: '3',
    name: 'Crab',
    code: 'SF003',
    stock: 15,
    pricePerKg: 8500.0,
    supplier: 'Sea Harvest',
    imagePath: 'assets/images/crab.jpeg',
  ),
  Product(
    id: '4',
    name: 'Shrimp',
    code: 'SF004',
    stock: 10,
    pricePerKg: 9000.0,
    supplier: 'Ocean Delight',
    imagePath: 'assets/images/shrimp.jpeg',
  ),
  Product(
    id: '5',
    name: 'Lobster',
    code: 'SF005',
    stock: 10,
    pricePerKg: 18000.0,
    supplier: 'Coral Bay Foods',
    imagePath: 'assets/images/lobster.jpeg',
  ),
  Product(
    id: '6',
    name: 'Catfish',
    code: 'SF006',
    stock: 25,
    pricePerKg: 2500.0,
    supplier: 'Riverfresh',
    imagePath: 'assets/images/catfish.jpeg',
  ),
  Product(
    id: '7',
    name: 'Oysters',
    code: 'SF007',
    stock: 40,
    pricePerKg: 10000.0,
    supplier: 'SBlue Ocean Traders',
    imagePath: 'assets/images/oysters.jpeg',
  ),
  Product(
    id: '8',
    name: 'Squid',
    code: 'SF008',
    stock: 18,
    pricePerKg: 7500.0,
    supplier: 'Blue Ocean Traders',
    imagePath: 'assets/images/squid.jpeg',
  ),
  Product(
    id: '9',
    name: 'Clams',
    code: 'SF009',
    stock: 22,
    pricePerKg: 7000.0,
    supplier: 'Blue Ocean Traders',
    imagePath: 'assets/images/clams.jpeg',
  ),
  
  
  Product(
    id: '10',
    name: 'Sardines',
    code: 'SF012',
    stock: 80,
    pricePerKg: 2200.0,
    supplier: 'Fisherman’s Choice',
    imagePath: 'assets/images/sardines.jpg',
  ),
  
  
  Product(
    id: '11',
    name: 'Periwinkle',
    code: 'SF015',
    stock: 45,
    pricePerKg: 1500.0,
    supplier: 'Riverfresh',
    imagePath: 'assets/images/periwinkle.jpg',
  ),
];
